name: HardcoreLists
version: 1.0.5
description: Hardcore player lists
author: Jeremaster101
main: xyz.jeremynoesen.hardcorelists.HardcoreLists
api-version: 1.13
commands:
  pvptime:
    description: Get the time remaining on your pvp timer
    usage: /<command>
    aliases: [pt]
  hardcorelists:
    description: HardcoreLists admin command. Use /hardcorelists help
    usage: /<command>
    aliases: [hl]

